### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by filip-we** [filip-we/pc_info_lcd#1]
**Stuff to be implemented**  
Listed in the same order they should be implemented.
- [ ] Define and implement protocol read- and write-functions
- [ ] Improve script and make it suitable for crontab-invocation
- [x] Separate communication and screen update
- [ ] Timeout for not displaying old values
- [ ] Add more types of data
- [x] Firmware support for dial nr 1, to adjust color
- [ ] Firmware support for dial nr 2, to alter behavior of LCD

**Comment by filip-we** [comment]
Changed objective for script: it should rather run as a daemon to be able to send values more often than every minute when cron runs it.
